### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by baugetfa**
I think it is important to merge last changes because of end of contract. See my comment below.

This is still WIP on documentation. However it is very closed to a descent doc (see doc/_build/html). 

There are different notebooks-tutorials explaining: use of rsml, use of existing architecture, adjustment procedure, etc.
There are the corresponding html doc see doc/_build/html: index, quick-start, usage, Modeling principle (theory).
There are few modification in source files related to documentation. 
Some API corresponding to some general scripts are still missing.

### CODE REVIEW

**Comment by pradal** [comment]
Can you fix first the conflicts?
It seems that you are not branched on the main branch

**Comment by pradal** [comment]
Also do not commi the _build dir. It will be regenerated automatically on readthedocs

**Comment by baugetfa** [comment]
Ok. I take care of that.

**Comment by baugetfa** [comment]
I close the request and I will resubmit one later. I an fixing conflict problems

**Pull request closed without merging**
